kind: Target
apiVersion: v1
name: git
imports:
  - name: http
    attach: imports/web
matedata:
  namespace: gitlab-apps
  labels:
    kuberes.git.resource: somevalue
  annotations:
    kuberes.git.generated: othervalue
resources:
  - resources/configMap.yaml

  - resources/service.yaml
  - resources/deployment.yaml
patchs:
  strategic:
    - patchs/add_init_container.yaml
    - patchs/add_service_annotation.yaml 
  rfc6902:
    - target:
        version: v1
        kind: Deployment
        name: my-deployment
      path: add_init_container.yaml
    - target:
        version: v1
        kind: Service
        name: my-service
      path: add_service_annotation.yaml 
