kind: Service
apiVersion: v1
metadata:
  name: gitlab-ce
spec:
  type: NodePort
  ports:
    - name: "ssh"
      protocol: TCP
      port: 22
      nodePort: 22
      targetPort: 22
    - name: "http"
      protocol: TCP
      port: 80
      nodePort: 80
      targetPort: 80
    - name: "https"
      protocol: TCP
      port: 443
      nodePort: 443
      targetPort: 443